export enum PermissionType {
	// Server-wide permissions
	MANAGE_SERVER = 'MANAGE_SERVER',
	KICK_MEMBERS = 'KICK_MEMBERS',
	BAN_MEMBERS = 'BAN_MEMBERS',
	MANAGE_ROLES = 'MANAGE_ROLES',
	INVITE_LINKS = 'INVITE_LINKS',
	CREATE_INVITE = 'CREATE_INVITE',
	SERVER_MEMBER = 'SERVER_MEMBER',

	// Channel permissions
	VIEW_CHANNEL = 'VIEW_CHANNEL',
	SEND_MESSAGES = 'SEND_MESSAGES',
	MANAGE_MESSAGES = 'MANAGE_MESSAGES',
	CONNECT = 'CONNECT',
	SPEAK = 'SPEAK',
	MUTE_MEMBERS = 'MUTE_MEMBERS',
	DEAFEN_MEMBERS = 'DEAFEN_MEMBERS',
}
