export enum RolePermissionType {
  // Server-wide permissions
  MANAGE_SERVER = 'MANAGE_SERVER',
  KICK_MEMBERS = 'KICK_MEMBERS',
  BAN_MEMBERS = 'BAN_MEMBERS',
  MANAGE_ROLES = 'MANAGE_ROLES',
  VIEW_AUDIT_LOG = 'VIEW_AUDIT_LOG',
  MANAGE_EMOJIS = 'MANAGE_EMOJIS',
  MANAGE_WEBHOOKS = 'MANAGE_WEBHOOKS',

  // Channel permissions
  VIEW_CHANNEL = 'VIEW_CHANNEL',
  SEND_MESSAGES = 'SEND_MESSAGES',
  MANAGE_MESSAGES = 'MANAGE_MESSAGES',
  CONNECT = 'CONNECT',
  SPEAK = 'SPEAK',
  MUTE_MEMBERS = 'MUTE_MEMBERS',
  DEAFEN_MEMBERS = 'DEAFEN_MEMBERS',
}
